In [5]:
%matplotlib inline
import numpy as np

In [7]:
# torch not installed yet
import torch

In [8]:
# creating np array from data
data=[[1,2],[3,4]]
nar=np.array(data)
nar

array([[1, 2],
       [3, 4]])

In [9]:
# creating tensor from data: 
ten=torch.tensor(data)
ten

tensor([[1, 2],
        [3, 4]])

In [10]:
# creating tensor from np array: 
ten1=torch.tensor(nar)
ten1

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [12]:
# creating np array from tensor: 
nar1=np.array(ten)
nar1

array([[1, 2],
       [3, 4]], dtype=int64)

In [13]:
ten2=torch.tensor(nar1)
ten2

tensor([[1, 2],
        [3, 4]])

In [15]:
data[0]=[9,10]
print(nar,nar1,ten,ten1,ten2,sep= "\\\n")

[[1 2]
 [3 4]]\
[[1 2]
 [3 4]]\
tensor([[1, 2],
        [3, 4]])\
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)\
tensor([[1, 2],
        [3, 4]])


In [29]:
nar[0]=[1,2]
print(nar)

# shallow copy
ten3=torch.from_numpy(nar)

# deep copy
ten4=torch.tensor(nar)

print(ten3,ten4, sep="\\\n")
nar[0]=[2,3]
print(ten3,ten4, sep="\\\n")

# nar and ten3 have same id
# not ten4
print(id(nar),id(ten3),id(ten4),sep='\n')


[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)\
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([[2, 3],
        [3, 4]], dtype=torch.int32)\
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
