In [27]:
# Initialisation

%matplotlib inline
import numpy as npj
import torch

# printer function
def p(t):
    # t is a tuple
    print(t)
    for i in t:
        print(i,end="\n-----------------------------\n")

In [3]:
# creating np array from data
data=[[1,2],[3,4]]
nar=np.array(data)
nar

array([[1, 2],
       [3, 4]])

In [4]:
# creating tensor from data: 
ten=torch.tensor(data)
ten

tensor([[1, 2],
        [3, 4]])

In [5]:
# creating tensor from np array: 
ten1=torch.tensor(nar)
ten1

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [6]:
# creating np array from tensor: 
nar1=np.array(ten)
nar1

array([[1, 2],
       [3, 4]], dtype=int64)

In [7]:
ten2=torch.tensor(nar1)
ten2

tensor([[1, 2],
        [3, 4]])

In [8]:
data[0]=[9,10]
print(nar,nar1,ten,ten1,ten2,sep= "\\\n")

[[1 2]
 [3 4]]\
[[1 2]
 [3 4]]\
tensor([[1, 2],
        [3, 4]])\
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)\
tensor([[1, 2],
        [3, 4]])


In [9]:
nar[0]=[1,2]
print(nar)

# shallow copy
ten3=torch.from_numpy(nar)

# deep copy
ten4=torch.tensor(nar)

print(ten3,ten4, sep="\\\n")
nar[0]=[2,3]
print(ten3,ten4, sep="\\\n")

# nar and ten3 have same id
# not ten4
print(id(nar),id(ten3),id(ten4),sep='\n')


[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)\
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([[2, 3],
        [3, 4]], dtype=torch.int32)\
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
2337070870384
2337062418096
2337031213280


In [10]:
# printer function
def p(t):
    # t is a tuple
    print(t)
    for i in t:
        print(i,end="\n-----------------------------\n")

In [29]:
# creating tensors of 1s and random valeus
print("Ten \n",ten)
x1=torch.ones_like(ten)

# dtype must be float!
# this is because the rand_like function is only implemented for FLOAT or DOUBLE types
x2=torch.rand_like(ten,dtype=torch.float)

try:
    x3=torch.rand_like(ten)
    p((x3))
except:
    print("error, dtype must be float not int")
try:
    x3=torch.rand_like(ten,dtype=int32)
    p((x3))
except:
    print("error, dtype must be float not int")
p((x1,x2))


Ten 
 tensor([[1, 2],
        [3, 4]])
error, dtype must be float not int
error, dtype must be float not int
tensor([[1, 1],
        [1, 1]])
-----------------------------
tensor([[0.9212, 0.2677],
        [0.7044, 0.1016]])
-----------------------------


In [ ]:
# shape is a tuple of dimensions of the tensor
shape = (2,3)
x1=torch.rand(shape)
print(x1)
shape2=(1,2,3,4)
x2=torch.zeros(shape2)
x2

In [29]:
x=torch.ones(2,3)
print('attributes are :')
print("tensor shape : ",x.shape)
print("tensor dtype : ",x.dtype)
print("tensor device : ",x.device)

attributes are :
tensor shape :  torch.Size([2, 3])
tensor dtype :  torch.float32
tensor device :  cpu
