In [2]:
# Initialisation

import numpy as np
import torch

In [46]:
# accessing sub-tensor is just like list
x=torch.tensor([[1,2],[3,4],[3,5]])
print(x)
print(x[0])
print(x[0][1])
print(x.size())

tensor([[1, 2],
        [3, 4],
        [3, 5]])
tensor([1, 2])
tensor(2)
torch.Size([3, 2])
2


In [43]:
# getting actual value
x=torch.tensor([[1,2],[3,4]])

print(x[0][1].item())
print(x[0][1].size())
print()
try:
    print(x[0].item())
except:
    print("item() works only on 0-D tensors , i.e. scalars")
    print(x[0].size())
    

2
torch.Size([])

item() works only on 0-D tensors , i.e. scalars
torch.Size([2])


In [49]:
# size and dimension :

# size is like rows,columns
x=torch.tensor([[1,2],[3,4],[3,5]])
print('size',x.size())

# dimension is rank
print('dimensions : ', x.dim())
print('another way :  ', x.ndimension())

size torch.Size([3, 2])
dimensions :  2
another way :   2


In [77]:
# random with seeding: remains constant over calls
seed= 123 
torch.manual_seed(seed)
x=torch.rand(2,3)
print(x)

tensor([[0.2961, 0.5166, 0.2517],
        [0.6886, 0.0740, 0.8665]])


In [112]:
# creating matrices from shape:
shape=(2,3)
x=torch.ones(shape)
x=torch.zeros(shape) #this sets values to zero
print(x)

#this doesnt intialise memeory at all so we may get any value
x=torch.empty(shape)  
print(x)


tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[6.7262e-44, 6.8664e-44, 1.1771e-43],
        [6.8664e-44, 7.0065e-44, 8.1275e-44]])
tensor([2., 3.])


In [118]:
# tensor vs Tensor:

# tensor infers datatype, but Tensor is alias for FloatTensor

print(torch.Tensor([1,2,3]).dtype)
# torch.float32

print(torch.tensor([1, 2, 3]).dtype)
# Out[32]: torch.int64

print(torch.Tensor([True, False]).dtype)
# torch.float32

print(torch.tensor([True, False]).dtype)
# torch.bool

torch.float32
torch.int64
torch.float32
torch.bool


In [122]:
# to()
# copying a tensor with changed data type
a=torch.Tensor([1,2,3])
print(a.dtype)
b=a.to(torch.int16)
print(b.dtype)

torch.float32
torch.int16


In [3]:
# in-place operations:
# start with _
x=torch.ones(2,3)
x.add_(5)
x

# warning: do not differentiate in place!

tensor([[6., 6., 6.],
        [6., 6., 6.]])

In [15]:
# numpy convert:
x=torch.ones(1,4)
n=x.numpy()
print(type(x),type(n))

print(x,n)
# changes reflected from parent to child
n=n+1
print(x,n)

x+=1
print(x,n)

<class 'torch.Tensor'> <class 'numpy.ndarray'>
tensor([[1., 1., 1., 1.]]) [[1. 1. 1. 1.]]
tensor([[1., 1., 1., 1.]]) [[2. 2. 2. 2.]]
tensor([[2., 2., 2., 2.]]) [[2. 2. 2. 2.]]


In [17]:
# numpy convert:
n=np.ones((1,4))
x=torch.tensor(n)
print(type(x),type(n))

print(x,n)
# changes reflected from parent to child
n=n+1
print(x,n)

x+=1
print(x,n)

<class 'torch.Tensor'> <class 'numpy.ndarray'>
tensor([[1., 1., 1., 1.]], dtype=torch.float64) [[1. 1. 1. 1.]]
tensor([[1., 1., 1., 1.]], dtype=torch.float64) [[2. 2. 2. 2.]]
tensor([[2., 2., 2., 2.]], dtype=torch.float64) [[2. 2. 2. 2.]]


In [20]:
# numpy convert:
n=np.ones((1,4))
x=torch.from_numpy(n)
print(type(x),type(n))

print(x,n)
# changes reflected from parent to child
n=n+1
print(x,n)

x+=1
print(x,n)
np.add(n, 1, out=n)
print(x,n)


<class 'torch.Tensor'> <class 'numpy.ndarray'>
tensor([[1., 1., 1., 1.]], dtype=torch.float64) [[1. 1. 1. 1.]]
tensor([[1., 1., 1., 1.]], dtype=torch.float64) [[2. 2. 2. 2.]]
tensor([[2., 2., 2., 2.]], dtype=torch.float64) [[2. 2. 2. 2.]]
tensor([[2., 2., 2., 2.]], dtype=torch.float64) [[3. 3. 3. 3.]]
