In [2]:
# Initialisation

import numpy as np
import math
import torch

In [9]:
x=torch.ones(2,3)
# scalar arithmetic operations are applied elementwise
x+4

tensor([[5., 5., 5.],
        [5., 5., 5.]])

In [6]:
x*3

tensor([[3., 3., 3.],
        [3., 3., 3.]])

In [16]:
(9+x)**2/4

tensor([[25., 25., 25.],
        [25., 25., 25.]])

In [26]:
# tensor multiplications / additions :
# require same dimensions:
# also performed elementwise
y=torch.ones_like(x)
y=y*5
print(x)
print(y)
x+y

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[5., 5., 5.],
        [5., 5., 5.]])


tensor([[6., 6., 6.],
        [6., 6., 6.]])

In [25]:
x*y

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[5., 5., 5.],
        [5., 5., 5.]])


tensor([[5., 5., 5.],
        [5., 5., 5.]])

In [29]:
try:
    a = torch.rand(2, 3)
    b = torch.rand(3, 2)

    print(a * b)
except:
    print("Error : tensor multiplications required tensors of same size")

Error : tensor multiplications required tensors of same size


In [33]:
# common functions
a = torch.rand(2, 4) * 2 - 1

# Simple Elementwise operations :
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
sines = torch.sin(a)
inverses = torch.asin(sines)

# clamp method:
print(torch.clamp(a, -0.5, 0.5))

# --------------------------------------
# Initialisation of matrices and vectors
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])


m1 = torch.rand(2, 2)                  
m2 = torch.tensor([[3., 0.], [0., 3.]])

# --------------------------------------
# Two tensor operands:

# Xor
print(torch.bitwise_xor(b, c))

# equality check
print(torch.eq(b,c)) # returns a tensor of type bool

# --------------------------------------
# reductions :
print('\nReduction ops:')

e = torch.rand(2, 4) * 2 - 1

# Statistics | return scalar :
print(torch.max(e))        # returns a single-element tensor
print(torch.max(e).item()) # extracts the value from the returned tensor
print(torch.mean(e))       # average
print(torch.std(e))        # standard deviation
print(torch.prod(e))       # product of all numbers

# returns subtensor:
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2]))) # filter unique elements

# --------------------------------------
# Vectors & Matrices:

# cross product
print(torch.cross(b,c)) # negative of z unit vector (v1 x v2 == -v2 x v1)

# matrix multiplication (not elementwise)

m3 = torch.matmul(m1, m2)

# singular value decomposition
# basically generalisation of diagonisation for non square matrices
# it returns a tuple of three matrices P,D,Q such that A= PDQ
# if A is square and diagonal then D is its diagonalised version and Q=P^1 (not sure, to test)
print(torch.svd(m3))    

tensor([[0.5145, 0.9846, 0.2785, 0.4585],
        [0.4936, 0.8233, 0.7879, 0.5465]])
tensor([[1., -0., -0., 1.],
        [1., 1., 1., -0.]])
tensor([[ 0., -1., -1.,  0.],
        [ 0.,  0.,  0., -1.]])
tensor([[ 0.5000, -0.5000, -0.2785,  0.4585],
        [ 0.4936,  0.5000,  0.5000, -0.5000]])
tensor([3, 2, 1])
tensor([False, False, False])

Reduction ops:
tensor(0.8794)
0.8793984651565552
tensor(0.0410)
tensor(0.5435)
tensor(5.5811e-06)
tensor([1, 2])
tensor([-27,  12,  -3])
torch.return_types.svd(
U=tensor([[-0.6609, -0.7505],
        [-0.7505,  0.6609]]),
S=tensor([3.2413, 1.3035]),
V=tensor([[-0.4748,  0.8801],
        [-0.8801, -0.4748]]))
